name: Deploy to Streamlit Community Cloud

# Trigger the workflow when pushing to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Install Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Optionally test the application (add your testing framework here)
      - name: Run tests (Optional)
        run: |
          echo "No tests defined, you can add them in the future."

      # Push changes to Streamlit Community Cloud
      - name: Push to GitHub
        run: |
          git config --global user.email "aqibrehmanpirzada75@gmail.com"
          git config --global user.name "aqibrehmanpirzada"
          git remote add origin https://github.com/aqibrehmanpirzada/Spirtual-Therapy-Bot-using-LLAMA-3-.git
          git push https://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@github.com/aqibrehmanpirzada/Spirtual-Therapy-Bot-using-LLAMA-3-.git HEAD:main
